"""Declarative registry of Aruba read-only endpoints exposed as MCP tools."""

from __future__ import annotations

from dataclasses import dataclass
from typing import Literal


@dataclass(frozen=True)
class Endpoint:
    name: str
    tool_name: str
    method: Literal["GET"]
    base: Literal["auth", "ws"]
    path_template: str
    params: tuple[str, ...]
    returns_binary: bool
    sensitive_read: bool
    rate_limit_bucket: str
    aruba_doc_section: str

    @property
    def endpoint_label(self) -> str:
        return f"{self.method} {self.path_template}"


ENDPOINTS: tuple[Endpoint, ...] = (
    Endpoint(
        "user_info",
        "aruba_get_user_info",
        "GET",
        "auth",
        "/auth/userInfo",
        (),
        False,
        False,
        "auth_read",
        "5.3 userInfo",
    ),
    Endpoint(
        "multicedenti",
        "aruba_list_multicedenti",
        "GET",
        "auth",
        "/auth/multicedenti",
        ("countryCode", "vatCode", "status", "size", "page"),
        False,
        False,
        "auth_read",
        "5.4 multicedenti",
    ),
    Endpoint(
        "multicedente_by_id",
        "aruba_get_multicedente_by_id",
        "GET",
        "auth",
        "/auth/multicedenti/{id}",
        ("id",),
        False,
        False,
        "auth_read",
        "5.5 multicedenteById",
    ),
    Endpoint(
        "find_sent_invoices",
        "aruba_find_sent_invoices",
        "GET",
        "ws",
        "/services/invoice/out/findByUsername",
        (
            "username",
            "page",
            "size",
            "startDate",
            "endDate",
            "countrySender",
            "vatcodeSender",
            "fiscalcodeSender",
            "countryReceiver",
            "vatcodeReceiver",
            "fiscalcodeReceiver",
        ),
        False,
        False,
        "find_sent",
        "8.2 findByUsername",
    ),
    Endpoint(
        "sent_invoice_by_filename",
        "aruba_get_sent_invoice_by_filename",
        "GET",
        "ws",
        "/services/invoice/out/getByFilename",
        ("filename", "includePdf", "includeFile"),
        False,
        True,
        "find_sent",
        "8.3 getByFilename",
    ),
    Endpoint(
        "sent_invoice_zip_by_filename",
        "aruba_get_sent_invoice_zip_by_filename",
        "GET",
        "ws",
        "/services/invoice/out/getZipByFilename",
        ("filename",),
        True,
        True,
        "find_sent",
        "8.4 getZipByFilename",
    ),
    Endpoint(
        "sent_invoice_by_id",
        "aruba_get_sent_invoice_by_id",
        "GET",
        "ws",
        "/services/invoice/out/{invoiceId}",
        ("invoiceId", "includePdf", "includeFile"),
        False,
        True,
        "find_sent",
        "8.5 getByInvoiceId",
    ),
    Endpoint(
        "sent_invoice_by_sdi_id",
        "aruba_get_sent_invoice_by_sdi_id",
        "GET",
        "ws",
        "/services/invoice/out/getByIdSdi",
        ("idSdi", "includePdf", "includeFile"),
        False,
        True,
        "find_sent",
        "8.6 getByIdSdi",
    ),
    Endpoint(
        "sent_invoice_pdd",
        "aruba_get_sent_invoice_pdd",
        "GET",
        "ws",
        "/services/invoice/out/pdd",
        ("invoiceFilename", "invoiceId"),
        True,
        True,
        "find_sent",
        "8.7 pdd",
    ),
    Endpoint(
        "find_received_invoices",
        "aruba_find_received_invoices",
        "GET",
        "ws",
        "/services/invoice/in/findByUsername",
        (
            "username",
            "page",
            "size",
            "startDate",
            "endDate",
            "countrySender",
            "vatcodeSender",
            "fiscalcodeSender",
            "countryReceiver",
            "vatcodeReceiver",
            "fiscalcodeReceiver",
        ),
        False,
        False,
        "find_received",
        "9.1 findByUsername",
    ),
    Endpoint(
        "received_invoice_by_filename",
        "aruba_get_received_invoice_by_filename",
        "GET",
        "ws",
        "/services/invoice/in/getByFilename",
        ("filename", "includePdf", "includeFile"),
        False,
        True,
        "find_received",
        "9.2 getByFilename",
    ),
    Endpoint(
        "received_invoice_zip_by_filename",
        "aruba_get_received_invoice_zip_by_filename",
        "GET",
        "ws",
        "/services/invoice/in/getZipByFilename",
        ("filename",),
        True,
        True,
        "find_received",
        "9.3 getZipByFilename",
    ),
    Endpoint(
        "received_invoice_by_id",
        "aruba_get_received_invoice_by_id",
        "GET",
        "ws",
        "/services/invoice/in/{invoiceId}",
        ("invoiceId", "includePdf", "includeFile"),
        False,
        True,
        "find_received",
        "9.4 getByInvoiceId",
    ),
    Endpoint(
        "received_invoice_by_sdi_id",
        "aruba_get_received_invoice_by_sdi_id",
        "GET",
        "ws",
        "/services/invoice/in/getByIdSdi",
        ("idSdi", "includePdf", "includeFile"),
        False,
        True,
        "find_received",
        "9.5 getByIdSdi",
    ),
    Endpoint(
        "received_invoice_unsigned_file",
        "aruba_get_received_invoice_unsigned_file",
        "GET",
        "ws",
        "/services/invoice/in/getInvoiceWithUnsignedFile",
        ("invoiceId", "filename", "includeFile"),
        False,
        True,
        "find_received",
        "9.6 getInvoiceWithUnsignedFile",
    ),
    Endpoint(
        "received_invoice_pdd",
        "aruba_get_received_invoice_pdd",
        "GET",
        "ws",
        "/services/invoice/in/pdd",
        ("invoiceFilename", "invoiceId"),
        True,
        True,
        "find_received",
        "9.7 pdd",
    ),
    Endpoint(
        "sent_notification_by_filename",
        "aruba_get_sent_notification_by_filename",
        "GET",
        "ws",
        "/services/notification/out/getByFilename",
        ("filename",),
        False,
        True,
        "notification_sent",
        "11.1 getByFilename",
    ),
    Endpoint(
        "sent_notifications_by_invoice_filename",
        "aruba_get_sent_notifications_by_invoice_filename",
        "GET",
        "ws",
        "/services/notification/out/getByInvoiceFilename",
        ("invoiceFilename",),
        False,
        True,
        "notification_sent",
        "11.2 getByInvoiceFilename",
    ),
    Endpoint(
        "sent_notifications_by_invoice_id",
        "aruba_get_sent_notifications_by_invoice_id",
        "GET",
        "ws",
        "/services/notification/out/{invoiceId}",
        ("invoiceId",),
        False,
        True,
        "notification_sent",
        "11.3 getByInvoiceId",
    ),
    Endpoint(
        "received_notification_by_filename",
        "aruba_get_received_notification_by_filename",
        "GET",
        "ws",
        "/services/notification/in/getByFilename",
        ("filename",),
        False,
        True,
        "notification_received",
        "12.1 getByFilename",
    ),
    Endpoint(
        "received_notifications_by_invoice_filename",
        "aruba_get_received_notifications_by_invoice_filename",
        "GET",
        "ws",
        "/services/notification/in/getByInvoiceFilename",
        ("invoiceFilename",),
        False,
        True,
        "notification_received",
        "12.2 getByInvoiceFilename",
    ),
    Endpoint(
        "received_notifications_by_invoice_id",
        "aruba_get_received_notifications_by_invoice_id",
        "GET",
        "ws",
        "/services/notification/in/{invoiceId}",
        ("invoiceId",),
        False,
        True,
        "notification_received",
        "12.3 getByInvoiceId",
    ),
    Endpoint(
        "customer_result_status",
        "aruba_get_customer_result_status",
        "GET",
        "ws",
        "/services/invoice/in/sendEsitoCommittente/{filename}",
        ("filename",),
        False,
        False,
        "find_received",
        "10.2 sendEsitoCommittente Status",
    ),
)

ENDPOINT_BY_NAME = {endpoint.name: endpoint for endpoint in ENDPOINTS}
ENDPOINT_BY_TOOL = {endpoint.tool_name: endpoint for endpoint in ENDPOINTS}
